/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Author {
  'id' : Principal,
  'displayName' : string,
  'avatar' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface PostMetadata {
  'id' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'author' : Author,
  'caption' : string,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPost' : ActorMethod<[string, ExternalBlob, Array<string>], PostMetadata>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<PostMetadata>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPosts' : ActorMethod<[string, [] | [string]], Array<PostMetadata>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];